object frmBasePadrao: TfrmBasePadrao
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  ClientHeight = 272
  ClientWidth = 636
  Color = clWhite
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Calibri'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 15
end
